### ISSUE TITLE
After running `node-reinstall ` I get npm ERR! Error: ENOENT, open 'package.js

### ISSUE THREAD

**Issue by ryansoper** [brock/node-reinstall#13]
I tried this on my mac but get these errors. I originally installed node as sudo, maybe that is my issue..

![image](https://cloud.githubusercontent.com/assets/2746655/6967502/9dccd274-d957-11e4-8e0f-46b3eb6786b4.png)

```
npm ERR! addLocal Could not install .
npm ERR! Error: ENOENT, open 'package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 12.5.0
npm ERR! command "/Users/me/.nvm/v0.10.38/bin/node" "/Users/me/.nvm/v0.10.38/bin/npm" "install" "--global"
npm ERR! cwd /Users/me
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! path package.json
npm ERR! code ENOENT
npm ERR! errno 34
```

**Comment by brock** [comment]
Thanks for reporting this @ryansoper 

It looks like this error happened at the end, right when it tried to re-install your global npm modules. I'll try to reproduce this and see if I can figure out exactly what is happening. 

Do you remember ever installing npm global modules? I'm wondering if you possibly didn't have any global modules, and so the installer might have tried running `npm install --global` (without any modules)

Also, would you mind checking to see if Node and NVM got installed? If it just failed re-installing global modules, you probably got Node and NVM re-installed just fine. You can run `which node` and `which nvm` to see where they are installed.

**Comment by brock** [comment]
Okay, I'm pretty sure this is the case. Steps to reproduce:

* Create an empty directory somewhere
* run this command `npm install --global`

I got this output which appears identical to what you got:
```
npm ERR! addLocal Could not install .
npm ERR! Error: ENOENT, open 'package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.1.0
npm ERR! command "/Users/brock/.nvm/v0.10.37/bin/node" "/Users/brock/.nvm/v0.10.37/bin/npm" "install" "--global"
npm ERR! cwd /Users/brock/research/test-reinstall
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! path package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/brock/research/test-reinstall/npm-debug.log
npm ERR! not ok code 0
```

I'll work on an update that confirms that there were global modules installed.

**Comment by QuantumInformation** [comment]
Great work!

On Thursday, 2 April 2015, Brock Angelo <notifications@github.com> wrote:

> Okay, I'm pretty sure this is the case. Steps to reproduce:
>
>    - Create an empty directory somewhere
>    - run this command npm install --global
>
> I got this output which appears identical to what you got:
>
> npm ERR! addLocal Could not install .
> npm ERR! Error: ENOENT, open 'package.json'
> npm ERR! If you need help, you may report this *entire* log,
> npm ERR! including the npm and node versions, at:
> npm ERR!     <http://github.com/npm/npm/issues>
>
> npm ERR! System Darwin 14.1.0
> npm ERR! command "/Users/brock/.nvm/v0.10.37/bin/node" "/Users/brock/.nvm/v0.10.37/bin/npm" "install" "--global"
> npm ERR! cwd /Users/brock/research/test-reinstall
> npm ERR! node -v v0.10.37
> npm ERR! npm -v 1.4.28
> npm ERR! path package.json
> npm ERR! code ENOENT
> npm ERR! errno 34
> npm ERR!
> npm ERR! Additional logging details can be found in:
> npm ERR!     /Users/brock/research/test-reinstall/npm-debug.log
> npm ERR! not ok code 0
>
> I'll work on an update that confirms that there were global modules
> installed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brock/node-reinstall/issues/13#issuecomment-88987498>.
>


-- 

Kind regards
Nikos

**Comment by brock** [comment]
@ryansoper would you mind to re-install this package and try it again? If you used bpkg, you can run `bpkg install -g brock/node-reinstall`
