### ISSUE TITLE
Add node and npm evn variable set functionality after install

### ISSUE THREAD

**Issue by maxpavlov** [brock/node-reinstall#23]
After I run node-reinstall I see in the output that everything went fine. Thumbs up.

I try to call either node or npm and those are not found.

I understand that this is probably by design, but this makes the tool useless. I don't know where it installed node and this makes me looking. So I just download .pkg from nodejs.org and use it. 

Please add the ability for the script to make node and npm available in console after reinstall. Thanks.

**Comment by brock** [comment]
You would need to restart the terminal. I will update the message at the output
