### ISSUE TITLE
node, npm, nvm - command not found after install

### ISSUE THREAD

**Issue by wintermute77** [brock/node-reinstall#26]
Am I missing something obvious?

➤ cd ~/
➤ bpkg install -g brock/node-reinstall

info: Install /brock/node-reinstall/master from remote https://raw.githubusercontent.com [https://github.com]
info: Cloning https://github.com/brock/node-reinstall.git to node-reinstall-master
Cloning into 'node-reinstall-master'...
remote: Counting objects: 175, done.
remote: Total 175 (delta 0), reused 0 (delta 0), pack-reused 175
Receiving objects: 100% (175/175), 31.10 KiB | 0 bytes/s, done.
Resolving deltas: 100% (83/83), done.
Checking connectivity... done.
info: Performing install: `make install'
cp node-reinstall.sh /usr/local/bin/node-reinstall
➤ which node-reinstall
/usr/local/bin/node-reinstall
➤ node-reinstall
Installing Node, npm.
=> Downloading nvm from git to '/Users/wintermute77/.nvm'
=> Cloning into '/Users/wintermute77/.nvm'...
remote: Counting objects: 4142, done.
remote: Total 4142 (delta 0), reused 0 (delta 0), pack-reused 4142
Receiving objects: 100% (4142/4142), 1.02 MiB | 0 bytes/s, done.
Resolving deltas: 100% (2406/2406), done.
Checking connectivity... done.
* (detached from v0.25.1)
master

=> Source string already in /Users/wintermute77/.bashrc
=> Close and reopen your terminal to start using nvm
######################################################################## 100.0%
Now using node v0.10.40 (npm v1.4.28)
default -> 0.10 (-> v0.10.40)
node-reinstall is done. 👍
You must restart your terminal for changes to take effect.

<< restart iTerm >>

➤ node -v
-bash: node: command not found

same for npm and nvm.

/usr/local/bin is now full of broken symlinks to ../lib/node_modules/
eg:
➤ file /usr/local/bin/bower
/usr/local/bin/bower: broken symbolic link to ../lib/node_modules/bower/bin/bower

Something fairly catastrophic seems to have happened. Any idea what?

**Comment by wintermute77** [comment]
Ok, it seems that - to my frankly clueless eye - the line:
source $HOME/.nvm/nvm.sh
wasn't.. doing whatever it should.

I ran
➤ . ~/.nvm/nvm.sh

and was then able to use nvm to install node and npm.

(I also added the relevant lines to my ~/.bash_profile from the "Manual Install" section on https://github.com/creationix/nvm, to load nvm automatically in future.)

Not sure what happened, but it seems to be working now..

**Comment by brock** [comment]
Thanks for reporting this issue @wintermute77 And thanks for posting all the logs.

I'm not immediately sure what happened in your situation, but I'll test this over the weekend and see if I can reproduce the issue.

**Comment by VoteAlex** [comment]
@wintermute77  I had the same error. I fixed it with changing the permission to the npm and node directory with "sudo chown -R `whoami` /usr/local/".

**Comment by brock** [comment]
Thanks @VoteAlex 

I've already changed ownership on my /usr/local directories - think it is homebrew that encouraged that initially - so I've never tested it with the defaults.

This might be worth adding as a prompt if the user doesn't already own them.

**Comment by brock** [comment]
I haven't been able to reproduce this issue, so I'm going to go ahead and close it for now. If you keep running into the issue, please feel free to leave another comment and I'll be happy to open this back up again.

Thanks again for reporting this, and I apologize that I haven't really found a solid solution.
