### ISSUE TITLE
"The script did not find any global node modules"

### ISSUE THREAD

**Issue by xinaesthete** [brock/node-reinstall#27]
Indeed, `npm -g list --depth 0 --parseable | xargs basename | sed -E 's/^(lib|npm)$//g'` doesn't return anything useful, but `npm -g list --depth 0` surely does. I haven't attempted to grok the rest of that line.

**Comment by xinaesthete** [comment]
Oh yeah, I was just running from an arbitrary local directory where I cloned the repo, not sure if that's important.

**Comment by brock** [comment]
what version of node were you using when you ran the script?

**Comment by xinaesthete** [comment]
Good question... I was taking notes as I went along, but I'm not sure if I captured that information. Will try to remember to have a second look in the morning.

**Comment by xinaesthete** [comment]
v0.10.28 I think.

**Comment by brock** [comment]
@xinaesthete did you install this using bpkg or by cloning the repo?

**Comment by xinaesthete** [comment]
Cloned the repo.

**Comment by xinaesthete** [comment]
I should add that I installed v4.2.2 via the installer from node website anyway. I notice that `npm -g list --depth 0 --parseable | xargs basename | sed -E 's/^(lib|npm)$//g'` is producing sensible looking output now as well. Haven't tried running your whole script again.

**Comment by xinaesthete** [comment]
Also, I'm on OS X; I don't think I'd even noticed that this project was supposed to be cross-platform when I first filed this as an issue and looking over my comments see that wasn't clear.

**Comment by brock** [comment]
@xinaesthete I haven't been able to reproduce this issue, but it might be related to the point raised over in #26 about the `/usr/local` directories not being owned by the current user. I'm going to close this issue for now, but if you run the script again and have issues, feel free to reopen it and paste in any logs you've got.

Thanks!

**Comment by xinaesthete** [comment]
Cheers

**Comment by bret-hubbard** [comment]
I had this same issue. To fix this, I had to change the command to npm -g list --depth 0 --parseable | xargs -n1 basename | sed -E 's/^(lib|npm)$//g' Thanks for the util!
