### ISSUE TITLE
Install a newer version of Node by default

### ISSUE THREAD

**Issue by brock** [brock/node-reinstall#31]
The script currently installs 0.10, but that is getting pretty outdated. #30 will take care of matching a version that is already installed, but for new installations I'm considering just bumping this to 5.0.

Open to thoughts if anyone has them.

NVM supports running `nvm install node` which is like `nvm install stable`. I'm open to that, but I'll have to see if Nave supports the same.

**Comment by kaona** [comment]
Good idea to set to 5 i think. No reason other than thats what im using it for. By the way, i cant get this to work. im on el capitain and tried all versions of the command from the node-reinstall directory. `Alains-MacBook-Pro:~ klik$ git clone git@github.com:brock/node-reinstall.git
Cloning into 'node-reinstall'...
remote: Counting objects: 188, done.
remote: Total 188 (delta 0), reused 0 (delta 0), pack-reused 188
Receiving objects: 100% (188/188), 35.93 KiB | 0 bytes/s, done.
Resolving deltas: 100% (90/90), done.
Checking connectivity... done.
Alains-MacBook-Pro:~ klik$ node-reinstall --nvm-latest
-bash: node-reinstall: command not found
Alains-MacBook-Pro:~ klik$ cd node-reinstall/
Alains-MacBook-Pro:node-reinstall klik$ ./node-reinstall --nvm-latest
-bash: ./node-reinstall: No such file or directory
Alains-MacBook-Pro:node-reinstall klik$ bash node-reinstall
bash: node-reinstall: No such file or directory
Alains-MacBook-Pro:node-reinstall klik$ ls
Makefile		node-reinstall.sh
README.md		package.json
Alains-MacBook-Pro:node-reinstall klik$ node-reinstall.sh --nvm-latest
-bash: node-reinstall.sh: command not found
Alains-MacBook-Pro:node-reinstall klik$ node-reinstall
-bash: node-reinstall: command not found
Alains-MacBook-Pro:node-reinstall klik$ ./node-reinstall
-bash: ./node-reinstall: No such file or directory
Alains-MacBook-Pro:node-reinstall klik$ bash node-reinstall
bash: node-reinstall: No such file or directory
Alains-MacBook-Pro:node-reinstall klik$ ./node-reinstall
-bash: ./node-reinstall: No such file or directory
Alains-MacBook-Pro:node-reinstall klik$ node-reinstall.sh
-bash: node-reinstall.sh: command not found
Alains-MacBook-Pro:node-reinstall klik$ cd node-reinstall.sh 
-bash: cd: node-reinstall.sh: Not a directory
Alains-MacBook-Pro:node-reinstall klik$ 
`

**Comment by brock** [comment]
@kaona Your syntax wasn't quite right. From the top, it would look like this:

```
git clone git@github.com:brock/node-reinstall.git
cd node-reinstall
bash node-reinstall.sh --nvm-latest
```

**Comment by brock** [comment]
@kaona My apologies, I just realized that the README is showing the incorrect commands.
