### ISSUE TITLE
-bash: node: command not found

### ISSUE THREAD

**Issue by leontyr** [brock/node-reinstall#37]
After finishing running ./node-reinstall and restarted my Mac, I still can't run any node/npm command.

When I check, there is no /usr/local/bin/node folder.

Could you please help?

Thanks,

**Comment by brock** [comment]
It should have installed the default Node (currently the version is "5") as part of the re-install. Can you check to see if you have `nvm` installed? Type this in the terminal: `which nvm`

If you don't see anything, check to see if you have the nvm directory:
`ls -alh ~/.nvm`

If you do have `nvm` available, you can see the available versions of Node by running `nvm list`.

Let me know if that turns up anything.

**Comment by leontyr** [comment]
Thanks for the reply.

`which nvm` returns nothing 

Here are the files shown after `ls -alh ~/.nvm`

```
.git
.gitattributes
.gitignore
.npmignore
.travis.yml
CONTRIBUTING.md
LICENSE.md
Makefile
README.markdown
alias
bash_completion
bin
install.sh
nvm-exec
nvm.sh
package.json
test
versions
```

`nvm list` returns `-bash: nvm: command not found`

**Comment by brock** [comment]
So it looks like nvm was installed on your machine, but your terminal doesn't know where to find it.

It might help to take a look at the documentation on the nvm page. Here is the section that talks about the install script and what it is doing. https://github.com/creationix/nvm#install-script

When nvm gets installed, it should have added the following lines to `~/.bash_profile`, `~/.profile` or `~/.bashrc`:

```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
```

Those lines are what would have told your terminal how to execute nvm, so something is missing. You should look to see if you have any of those files `~/.bash_profile`, `~/.profile` or `~/.bashrc`, and then check to see if the one you have has those lines at the bottom.

**Comment by leontyr** [comment]
Thank you @brock !
