### ISSUE TITLE
Add path for Homebrew && ./node-gyp

### ISSUE THREAD

**Issue by musicEnfanthen** [brock/node-reinstall#42]
Thanks for the great script. Everything worked fine here (MacOS 10.10.5, Node v.6.6.0).

Just one thougt: If you installed node via Homebrew you should also `brew uninstall node`
after or before running the script. Maybe you want to add this to the `README.md` or include it in the script itself? 

Additionally there could be a `~/.node-gyp` folder in the home directory, that can be deleted safely according to [this SO article](http://stackoverflow.com/a/19997205).

**Comment by brock** [comment]
I believe this is fixed now, but if not, feel free to re-open
